In [1]:
import numpy as np

In [2]:
arrayList=[1,2,3,4,5]
np.array(arrayList)

array([1, 2, 3, 4, 5])

In [3]:
np.ones((2,3)) #data type is float by default

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.zeros((2,3)) #data type is float by default
np.zeros((2,3),dtype=np.int32)# change datatype to int

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
np.empty((2,3)) #faster than zero/ones but we have to put the values later

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.eye(2,dtype=np.int32)# creates a identity Square matrix

array([[1, 0],
       [0, 1]])

In [12]:
np.arange(2,24,2)#(lowerbound,upperbound,increment)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [13]:
np.arange(8)#upperbound increment=1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
arr=np.ones((2,3))
np.ones_like(arr)# creates a np array with the shape of arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
arr.reshape((3,2))# reshape the array it was 2X3 Now it is 3X2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.array([(1,2,3),(4,5,6)])# numpy array using list of tuples

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.arange(36).reshape(3,4,3) # 3 dimension 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [20]:
np.arange(1200)# to avoid the elipses use set_printoptions

array([   0,    1,    2, ..., 1197, 1198, 1199])

In [25]:
np.set_printoptions(threshold=3000)

In [26]:
np.arange(1200)

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
        110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
        121,  122,  123,  124,  125,  126,  127,  128,  129,  130,  131,
        132,  133,  134,  135,  136,  137,  138,  139,  140,  141,  142,
        143,  144,  145,  146,  147,  148,  149,  1

In [27]:
np.array([1,2,3])+np.array([4,5,6])# element wise +-/*

array([5, 7, 9])

In [28]:
np.array([1,2,3])*2#array * by scalar +-/*%

array([2, 4, 6])

In [30]:
x=np.array([[1,2,3],[4,5,6]])

In [31]:
x.sum()# any aggregate function min max 

21

In [32]:
x.sum(axis=0)# column wise sum

array([5, 7, 9])

In [33]:
x.sum(axis=1)# row wise sum

array([ 6, 15])

### UNIVERSAL FUNCTIONS

In [39]:
radius=np.arange(4)
print(radius)
np.pi*radius** 2

[0 1 2 3]


array([ 0.        ,  3.14159265, 12.56637061, 28.27433388])

In [43]:
AnglesRadian=np.arange(4)*np.pi/180
print(AnglesRadian)
np.sin(AnglesRadian)##Similarly np.tan np.cos

[0.         0.01745329 0.03490659 0.05235988]


array([0.        , 0.01745241, 0.0348995 , 0.05233596])

In [45]:
np.arcsin(np.sin(AnglesRadian))# original radian angle

array([0.        , 0.01745329, 0.03490659, 0.05235988])

In [47]:
arr=np.arange(6)
print(np.mean(arr),np.median(arr),np.var(arr),np.std(arr),"Exp:",np.exp(arr),"SquareRoot:",np.sqrt(arr))

2.5 2.5 2.9166666666666665 1.707825127659933 Exp: [  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ] SquareRoot: [0.         1.         1.41421356 1.73205081 2.         2.23606798]


### Slicing and indexing

In [51]:
arr1=np.arange(9)
arr1[2:7] #lowerbound index upperbound index 

array([2, 3, 4, 5, 6])

In [52]:
arr1[::-1]# reverse a arr1

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [58]:
arr2=arr1.reshape((3,-1))
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
arr2[...,0]# all rows of 1st column and we can use elipse instead of :

array([0, 3, 6])

In [60]:
for row in arr2:
    print("Row",row)

Row [0 1 2]
Row [3 4 5]
Row [6 7 8]


In [62]:
print(arr2.flatten()) # rowise
print(arr2.flatten(order='F'))# column wise

[0 1 2 3 4 5 6 7 8]
[0 3 6 1 4 7 2 5 8]


In [65]:
for i in np.nditer(arr2):# use op_flags to change i to write as by default it is read only # order to change to Column wise
    print(i)

0
1
2
3
4
5
6
7
8


In [67]:
arr2.ravel() # Differance between ravel/flatten is ravel is a function of numpy and  flatten is a function of numpy array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])